name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install dependencies
      run: |
        cd Mobile_App
        npm install
    
    - name: Create .env file
      run: |
        cd Mobile_App
        echo "API_URL=https://backend-sql-9ck0.onrender.com/api/v1" > .env
    
    - name: Build APK
      run: |
        cd Mobile_App
        npx expo prebuild --platform android
        cd android
        chmod +x ./gradlew
        ./gradlew assembleRelease
    
    - uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: Mobile_App/android/app/build/outputs/apk/release/app-release.apk
